config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'apply', to: 'pages#apply' #new user application form
  get 'start', to: 'pages#start' #new user onboarding

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  # resources :dashboard, only: [:index]
  get 'dashboard', to: 'dashboard#index'
  get 'stakeholder_updates/new', to: 'stakeholder_updates#new'

  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]


  resources :user_submissions, only: [:create]


  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  namespace :admin do
    get '/', to: 'pages#dashboard'
    resources :user_submissions, only: [:update]
  end

  # admin panels
  # authenticated :user, -> user { user.admin? } do
  #   namespace :admin do
  #     resources :dashboard, only: [:index]
  #     resources :impersonations, only: [:new]
  #     resources :users, only: [:edit, :update, :destroy]
  #   end
  #
  #   # convenience helper
  #   get 'admin', to: 'admin/dashboard#index'
  # end
end

app/views/admin/pages/dashboard.html.erb
<%= render partial: "shared/heading", locals: {title: 'Admin Panel', tagline: "Accept or Reject Applications"} %>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Plan</th>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Email</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Website</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Role</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Newsletter</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">

              <% @user_submissions.each do |user_submission| %>
                <tr>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                    <div class="flex items-center">
                      <!-- TO-DO demonstrate how to do avatars with GRAVATAR -->
                      <!-- <div class="h-10 w-10 flex-shrink-0">
                        <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                      </div> -->
                      <div class="ml-4">
                        <div class="font-medium text-gray-900">
                          <%= user_submission.name %></div>
                      </div>
                    </div>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= user_submission.plan_name %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= user_submission.email %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= user_submission.website %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= user_submission.job_role %></td>
                  <td class="px-3 py-4 text-sm text-gray-500 max-w-xs">
                    <div class="text-gray-900"></div>
                      <%= user_submission.text %>
                  </td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <div>
                      <%= form_for user_submission, url: admin_user_submission_path(user_submission) do |f| %>
                        <select id="user_submission_status" name="user_submission[status]" class="mt-1 mb-2 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm">
                          <option <%= 'selected' if user_submission.status.nil? %>>Pending</option>
                          <option <%= 'selected' if user_submission.status == "Approve" %>>Approve</option>
                          <option <%= 'selected' if user_submission.status == "Reject" %>>Reject</option>
                        </select>
                        <%= f.submit 'Update', class: "w-full inline-flex justify-center rounded-md border border-transparent bg-brand-blue hover:bg-brand-blue-dark py-2 px-4 text-sm font-medium text-white shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
                      <% end %>
                  </div>
                  </td>
                </tr>
              <% end %>



              <!-- More people... -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>