config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'apply', to: 'pages#apply' #new user application form
  get 'start', to: 'pages#start' #new user onboarding

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  # resources :dashboard, only: [:index]
  get 'dashboard', to: 'dashboard#index'
  get 'stakeholder_updates/new', to: 'stakeholder_updates#new'

  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]


  resources :user_submissions, only: [:create]


  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  namespace :admin do
    get '/', to: 'pages#dashboard'
    resources :user_submissions, only: [:update]
  end

  # admin panels
  # authenticated :user, -> user { user.admin? } do
  #   namespace :admin do
  #     resources :dashboard, only: [:index]
  #     resources :impersonations, only: [:new]
  #     resources :users, only: [:edit, :update, :destroy]
  #   end
  #
  #   # convenience helper
  #   get 'admin', to: 'admin/dashboard#index'
  # end
end

app/views/shared/_flash.html.erb
<% visibility = 'hidden' unless (flash[:alert].present? || flash[:notice].present?) %>

<div class="<%= visibility %> md:grid md:grid-cols-3 md:gap-6 mt-12">
  <div class="md:col-span-1"></div>
  <div class="md:col-span-1">
    <% if flash[:alert].present? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">Uh oh!</strong>
        <span class="block sm:inline"><%= alert %></span>
        <span id="flash_alert_close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
        </span>
      </div>
    <% end %>

    <% if flash[:notice].present? %>
    <div class="bg-lightgreen-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Cool!</strong>
      <span class="block sm:inline"><%= notice %></span>
      <span id="flash_alert_close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
      </span>
    </div>
    <% end %>
  </div>
</div>

<!-- Flash management -->
<script type="text/javascript">
  var flashAlert = document.getElementById('flash_alert_close');
  if (flashAlert !== null) {
    document.getElementById('flash_alert_close').addEventListener('click', function() {
      this.parentElement.remove();
    });
  }
</script>

app/views/shared/_footer.html.erb
<!-- footer -->

<footer class="bg-white">
  <div class="mx-auto max-w-7xl py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center space-x-6 md:order-2">

      <a href="https://twitter.com/rohunjauhar" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      </a>

      <a href="https://github.com/rohunj/founder_digest" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>

    </div>
    <div class="mt-8 md:order-1 md:mt-0">
      <p class="text-center text-base text-gray-400">&copy; <%= Date.today.year %> Founder Digest, All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="py-4 px-2" data-controller="header">
  <nav class="flex items-center justify-between flex-wrap">
    <div class="flex items-center flex-no-shrink text-white mr-6">
      <% logo_path = current_user ? dashboard_index_path : root_path %>
      <%= link_to logo_path do %>
        <%= image_tag "avatar.png",  style: "max-height: 42px" %>
        <%= image_tag "logo.png",  style: "max-height: 35px" %>
      <% end %>
      <span class="font-semibold text-xl tracking-tight"><%= ENV['company_name'] %></span>
    </div>
    <div class="block sm:hidden">
      <button class="navbar-burger flex items-center px-3 py-2 border rounded text-white border-white hover:text-white hover:border-white" data-action="click->header#toggleMobileNav">
        <svg class="text-black fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
        </svg>
      </button>
    </div>

    <div id="main-nav" class="w-full flex-grow sm:flex text-right sm:w-auto hidden" data-header-target="mainNav">
      <div class="text-sm sm:flex-grow">
        <% nav_link_classes = 'ml-8 whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900' %>
          <%# #TODO: ensure only admin can see admin link %>
          <a class="<%=nav_link_classes%>" href="/admin">Admin</a>
          <a class="<%=nav_link_classes%>" href="/dashboard">Dashboard</a>
          <a class="<%=nav_link_classes%>" href="/logout">Logout</a>
      </div>
    </div>
  </nav>
</header>


<!-- smooth scroll nav links -->
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>

app/views/shared/_heading.html.erb
<div class="text-center mb-8">
  <h3 class="text-lg font-medium leading-6 text-gray-900"><%= title %></h3>
  <p class="mt-1 text-sm text-gray-500"><%= tagline.html_safe %></p>
</div>

app/views/shared/_script_tags.html.erb
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>